[settings]
DEBUG=true
ALLOWED_HOSTS=['*']
INTERNAL_IPS=['127.0.0.1', ]
DOMAIN_URL="http://127.0.0.1:8000"

[smtp]
EMAIL_HOST="smtp-fra1t.alwaysdata.net"
EMAIL_PORT="465"
EMAIL_USE_TLS=false
EMAIL_USE_SSL=true
