# Generated by Django 3.1 on 2020-08-30 14:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_postcommentmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='comments.postcommentmodel', verbose_name='Parent comment'),
        ),
    ]
