# Generated by Django 3.1 on 2020-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200830_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommentmodel',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Is moderated'),
        ),
    ]
