# Generated by Django 3.1 on 2020-09-05 11:13

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200830_1435'),
        ('comments', '0004_postcommentmodel_is_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='post',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='news.postmodel', verbose_name='Post'),
        ),
    ]
