# Generated by Django 3.1 on 2020-09-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200830_1435'),
        ('comments', '0005_auto_20200905_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='news.postmodel', verbose_name='Post'),
        ),
    ]
