# Generated by Django 3.1 on 2020-09-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200905_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcommentmodel',
            old_name='is_moderated',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='local_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Local id'),
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
