# Generated by Django 3.1 on 2020-09-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20200909_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentmodel',
            name='avatar',
        ),
    ]
