# Generated by Django 3.1 on 2020-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesocialnetmodel',
            options={'ordering': ['title'], 'verbose_name': 'Social net', 'verbose_name_plural': 'Social nets'},
        ),
        migrations.AlterField(
            model_name='sitesocialnetmodel',
            name='title',
            field=models.CharField(max_length=18, unique=True, verbose_name='Social net'),
        ),
    ]
