# Generated by Django 3.1 on 2020-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200830_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesocialnetmodel',
            name='title_en',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='Social net'),
        ),
        migrations.AddField(
            model_name='sitesocialnetmodel',
            name='title_ru',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='Social net'),
        ),
        migrations.AddField(
            model_name='sitesocialnetmodel',
            name='url_en',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='sitesocialnetmodel',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
