# Generated by Django 3.1 on 2020-08-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200830_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocialnetmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='sitesocialnetmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sitesocialnetmodel',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='sitesocialnetmodel',
            name='url_ru',
        ),
    ]
