# Generated by Django 3.1 on 2020-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20200830_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemainsettingsmodel',
            name='deleted_avatar',
            field=models.ImageField(default=1, upload_to='images/settings', verbose_name='Deleter avatar'),
            preserve_default=False,
        ),
    ]
